class Search {
    //1. create and initiate the object
    constructor() {
        /* ordering matters. This needs to be placed before everything else. */
        this.addSearchHTML()
        this.searchResultsDiv = document.querySelector('#search-overlay__results')
        this.openButton = document.querySelectorAll('.js-search-trigger')
        this.closeButton = document.querySelector('.search-overlay__close')
        this.searchOverlay = document.querySelector('.search-overlay')
        this.isOverlayOpen = false
        this.isSpinnerVisible = false
        this.searchField = document.querySelector('#search-term')
        
        this.allInputs = document.querySelectorAll('input, textarea')
        this.previousValue
        this.typingTimer
        this.events()
    }
    //2. events
    events() {
        this.openButton[0].addEventListener('click', this.openOverlay.bind(this))
        this.openButton[1].addEventListener('click', this.openOverlay.bind(this))
        this.closeButton.addEventListener('click', this.closeOverlay.bind(this))
        document.addEventListener('keydown', this.keyPressDispatcher.bind(this))
        this.searchField.addEventListener('keyup', this.typingConstruct.bind(this))
    }
    //3. methods (or functions)

    openOverlay() {
        this.searchOverlay.classList.add('search-overlay--active')
        document.body.classList.add('body-no-scroll')
        this.searchField.value = ``
        setTimeout(() => this.searchField.focus(), 301)
        this.isOverlayOpen = true
    }
 
    closeOverlay() {
        this.searchOverlay.classList.remove('search-overlay--active')
        document.body.classList.remove('body-no-scroll')
        this.isOverlayOpen = false
        
    }

    keyPressDispatcher(e) {
        if (e.key === 's' && !this.isOverlayOpen && this.checkFocus(this.allInputs)) {
            this.openOverlay()
            // this.isOverlayOpen = true
        }

        if (e.key === 'Escape' && this.isOverlayOpen && this.checkFocus(this.allInputs)) {
            this.closeOverlay()
            // this.isOverlayOpen = false
        }
    }

    typingConstruct() {
        
        if (this.searchField.value !== this.previousValue) {
            clearTimeout(this.typingTimer)

            if (this.searchField.value) {
                if (!this.isSpinnerVisible) {
                    this.searchResultsDiv.innerHTML = `<div class="spinner-loader"></div>`
                    this.isSpinnerVisible = true
                }
                this.typingTimer = setTimeout(this.getSearchResults.bind(this), 750)
            } else {
                this.searchResultsDiv.innerHTML = ``
                this.isSpinnerVisible = false
            }
        }

        this.previousValue = this.searchField.value
    }

    async renderHTML() {
        const apiResPost = fetch(`${bcodingData.root_url}/wp-json/wp/v2/posts?search=${this.searchField.value}`).then((response) => response.json())
        const apiResPage = fetch(`${bcodingData.root_url}/wp-json/wp/v2/pages?search=${this.searchField.value}`).then((response) => response.json())
        const data = await Promise.all([apiResPost, apiResPage])
        this.searchResultsDiv.innerHTML = `
        <h2 class="search-overlay__section-title">Search Results</h2>
        <ul class="link-list min-list">
            ${!data[0].length && !data[1].length ? `<p>No result matches your search<p>` :
            `${data[0].map(arr => `<li><a href="${arr.link}">${arr.title.rendered}</a> by ${arr.authorName}</li>`).join(''). concat(data[1].map(arr => `<li><a href="${arr.link}">${arr.title.rendered}</a></li>`).join(''))}    
        </ul> `}`
    }

    getSearchResults() {
        this.renderHTML()
            .catch(e => {
                this.searchResultsDiv.innerHTML = `<p>Unexpected error. Please try again.</p>`
        })
        this.isSpinnerVisible = false
    }

    checkFocus(all) {
		//loops through all inputs
		for (const el of all) {
			//checks if any of the inputs have focus
			//returns false as soon as it finds focused elements
			if (document.activeElement == el) return false;
		}
		//else return true
		return true;
    }
    
    addSearchHTML() {
        // create a new element
        const elem = document.createElement('div');
        // set a class attribute
        elem.setAttribute('class', 'search-overlay');
        // Add all the html (except for the outer div as that has been generated by the new element)
        elem.innerHTML = `
        <div class="search-overlay__top">
            <div class="container">
            <i class="fa fa-search search-overlay__icon" aria-hidden="true"></i>
            <input type="text" class="search-term" id="search-term" placeholder="Type and search..." />
            <i class="fa fa-window-close search-overlay__close" aria-hidden="true"></i>
            </div>
        </div>
    
        <div class="container">
            <div id="search-overlay__results"></div>
        </div>`
    
    // append the new element to the body
        document.body.append(elem);
    }
}
 
export default Search;


